version: "3"

services:
  tileserver:
    image: maptiler/tileserver-gl:v4.5.1
    volumes:
      - ./data:/data
      - ./config:/config
      - ./styles:/styles
    ports:
      - "8080:8080"
    command: -c /config/tileserver.json
